const questions = [
  { text: 'Had a wank?', weight: 1 },
  { text: 'Had a wank in a public place?', weight: 2 },
  { text: 'Had a wank with someone else in the room?', weight: 3 },
  { text: 'Had a wank with an inanimate object?', weight: 2 },
  { text: 'Been caught wanking?', weight: 3 },
  { text: 'Had a wank in university buildings?', weight: 3 },
  
  { text: 'Held hands?', weight: 1 },
  { text: 'Been in a relationship?', weight: 2 },
  { text: 'Had a kiss?', weight: 1 },
  { text: 'Has a kiss longer than 30 seconds?', weight: 2 },
  { text: 'Gave or received a hickey?', weight: 1 },
  { text: 'Felt up or had your tits felt up?', weight: 2 },
  { text: 'Felt up or had your ass felt up?', weight: 2 },
  { text: 'Sent a nude?', weight: 2 },
  { text: 'Received a nude?', weight: 2 },
  { text: 'Dry humped?', weight: 2 },
  { text: 'Gave head?', weight: 2 },
  { text: 'Received head?', weight: 2 },
  { text: 'Gave or received period head?', weight: 3 },
  { text: 'Gave anal head?', weight: 3 },
  { text: 'Received anal head?', weight: 3 },
  { text: 'Ate someone\'s cum?', weight: 2 },
  { text: 'Showered with someone sexually?', weight: 3 },
  
  { text: 'Lost your virginity?', weight: 3 },
  { text: 'Shagged in a public place?', weight: 4 },
  { text: 'Shagged in university buildings?', weight: 4 },
  { text: 'Had period sex?', weight: 3 },
  { text: 'Had anal sex?', weight: 4 },
  { text: 'body count is more than or equal to 1?', weight: 2 },
  { text: 'body count is more than or equal to 5?', weight: 3 },
  { text: 'body count is more than or equal to 10?', weight: 4 },
  { text: 'body count is more than or equal to 20?', weight: 5 },
  { text: 'body count is more than 30+?', weight: 6 },
  { text: 'Had sex with 2 people in one day?', weight: 3 },
  { text: 'Had sex with 3 people in one day?', weight: 4 },
  { text: 'Had sex with 4 people in one day?', weight: 5 },
  { text: 'Had sex with 5 or more people in one day?', weight: 6 },
  { text: 'Shagged a MILF/DILF (must have a kid)?', weight: 4 },
  { text: 'Shagged a prostitute?', weight: 4 },
  { text: 'been to a strip club?', weight: 2 },
  { text: 'Been to a kink party?', weight: 4 },
  { text: 'Had a threesome?', weight: 4 },
  { text: 'Threesome with 2 of the opposite sex?', weight: 4 },
  { text: 'Had a foursome?', weight: 5 },
  { text: 'Had a foursome with 3 of the opposite sex?', weight: 5 },
  { text: 'Had a orgy? (5 or more people)', weight: 7 },
  { text: 'Shagged in a pub?', weight: 2 },
  { text: 'Shagged in a club?', weight: 3 },
  { text: 'Cheated on your partner?', weight: 3 },
  { text: 'Shagged someone you met on a night out?', weight: 3 },
  { text: 'Shagged in a car?', weight: 3 },
  { text: 'Joined the mile high club?', weight: 6 },
  { text: 'Travelled more than 3 hours for sex?', weight: 4 },
  { text: 'Shagged a virgin?', weight: 3 },
  { text: 'Shagged without a condom?', weight: 3 },
  { text: 'Had a STI scare?', weight: 3 },
  { text: 'Had a STI?', weight: 4 },
  { text: 'Made a porno?', weight: 4 },
  { text: 'Had a pregnancy scare?', weight: 5 },
  { text: 'Made someone pregnant or was pregnant?', weight: 6 },
  
  { text: 'Drank alcohol?', weight: 1 },
  { text: 'Thrown up while drinking?', weight: 1 },
  { text: 'Blacked out from drinking?', weight: 2 },
  { text: 'Gone to a lecture hungover?', weight: 2 },
  { text: 'Gone to work on a hangover?', weight: 3 },
  { text: 'Vaped nicotine?', weight: 1 },
  { text: 'Smoked a cigarette?', weight: 1 },
  { text: 'Smoked Weed?', weight: 2 },
  { text: 'Eaten edibles?', weight: 2 },
  { text: 'Greened out?', weight: 3 },
  { text: 'Used Noss canisters?', weight: 2 },
  { text: 'Used MDMA?', weight: 3 },
  { text: 'Used speed?', weight: 4 },
  { text: 'Used Cocaine?', weight: 3 },
  { text: 'Used Ketamine?', weight: 3 },
  { text: 'Used LSD?', weight: 4 },
  { text: 'Used Shrooms?', weight: 4 },
  { text: 'Used DMT?', weight: 6 },
  { text: 'Used any research chemicals?', weight: 6 },
  { text: 'Gone to a lecture on a comedown?', weight: 4 },
  { text: 'Gone to work on a comedown?', weight: 3 },
  { text: 'Raided your household medicine cabinet?', weight: 2 },
  { text: 'Raided other people\'s medicine cabinet?', weight: 4 },
  { text: 'Used 2 or more drugs together?', weight: 3 },
  { text: 'Used 3 or more drugs together?', weight: 4 },
  { text: 'Overdosed?', weight: 6 },
  { text: 'Used heroin?', weight: 6 },
  { text: 'Used crack/meth?', weight: 6 },
  { text: 'Ended up in a hospital from drug use?', weight: 4 },
  { text: 'Ended up in a psych ward from drug use?', weight: 6 },
  { text: 'Start your pre\'s at or before 10pm?', weight: 1 },
  { text: 'Start your pre\'s at or before 8pm?', weight: 1 },
  { text: 'Start your pre\'s at or before 6pm?', weight: 2 },
  { text: 'Start your pre\'s  at or before 4pm?', weight: 3 },
  { text: 'Start your pre\'s at or before 1pm?', weight: 5 },
  { text: 'Been to an afters?', weight: 2 },
  { text: 'Been to an afters that lasted until 7am?', weight: 4 },
  { text: 'Been on a 2 or more day bender?', weight: 2 },
  { text: 'Been on a 4 day bender?', weight: 4 },
  { text: 'Been on a 6 day bender?', weight: 5 },
  { text: 'Been on a week or more bender?', weight: 7 },
  
  { text: 'Stole food from a flatmate?', weight: 2 },
  { text: 'Vandalised something on purpose?', weight: 2 },
  { text: 'Used transport without paying?', weight: 2 },
  { text: 'Shoplifted on purpose?', weight: 3 },
  { text: 'Been banned from a store?', weight: 3 },
  { text: 'Been thrown out of a pub?', weight: 3 },
  { text: 'Been barred from a pub?', weight: 3 },
  { text: 'Been thrown out of a club?', weight: 3 },
  { text: 'Been barred from a club?', weight: 3 },
  { text: 'Been in a fight on a night out?', weight: 4 },
  { text: 'Had the police called on you?', weight: 4 },
  { text: 'Ran from the police?', weight: 4 },
  { text: 'Been placed in handcuffs?', weight: 5 },
  { text: 'Spent a night in a cell?', weight: 5 },
  { text: 'Got a citation from the police?', weight: 5 },
  { text: 'Got a criminal conviction?', weight: 5 },
  
  { text: 'Spent more than £50 on a single night out?', weight: 1 },
  { text: 'Spent more than £100 on a single night out?', weight: 2 },
  { text: 'Spent more than £200 on a single night out?', weight: 2 },
  { text: 'Spent more than £300 on a single night out?', weight: 3 },
  { text: 'Spent more than £400 on a single night out?', weight: 4 },
  { text: 'Spent more than £500 on a single night out?', weight: 5 },
  { text: 'Lost wallet or phone on a night out?', weight: 2 },
  { text: 'Been robbed on a night out?', weight: 3 },
  
  { text: 'Ended up in a hospital due to a night out?', weight: 4 },
  { text: 'Got a noise complaint from the university?', weight: 1 },
  { text: 'Got a fine from the university?', weight: 2 },
  { text: 'Got kicked out of the university?', weight: 2 },
  ]