const universities = [
  { name: "Im a retard and dont go to uni", aliases: ["None"] },
  { name: "University of Aberdeen", aliases: ["Aberdeen", "UoA"] },
  { name: "Aberystwyth University", aliases: ["Aberystwyth", "Aber"] },
  { name: "Anglia Ruskin University", aliases: ["Anglia Ruskin", "ARU"] },
  { name: "Aston University", aliases: ["Aston"] },
  { name: "Bangor University", aliases: ["Bangor"] },
  { name: "University of Bath", aliases: ["Bath"] },
  { name: "University of Bedfordshire", aliases: ["Bedfordshire", "Beds"] },
  { name: "University of Birmingham", aliases: ["Birmingham", "UoB"] },
  { name: "Birmingham City University", aliases: ["Birmingham City", "BCU"] },
  { name: "University of Bolton", aliases: ["Bolton"] },
  { name: "Bournemouth University", aliases: ["Bournemouth", "BU"] },
  { name: "University of Bradford", aliases: ["Bradford"] },
  { name: "University of Brighton", aliases: ["Brighton"] },
  { name: "University of Bristol", aliases: ["Bristol"] },
  { name: "Brunel University London", aliases: ["Brunel"] },
  { name: "University of Buckingham", aliases: ["Buckingham"] },
  { name: "Buckinghamshire New University", aliases: ["Buckinghamshire New", "Bucks New"] },
  { name: "University of Cambridge", aliases: ["Cambridge"] },
  { name: "Canterbury Christ Church University", aliases: ["Canterbury Christ Church", "CCCU"] },
  { name: "Cardiff University", aliases: ["Cardiff"] },
  { name: "University of Central Lancashire", aliases: ["Central Lancashire", "UCLan"] },
  { name: "University of Chester", aliases: ["Chester"] },
  { name: "University of Chichester", aliases: ["Chichester"] },
  { name: "City, University of London", aliases: ["City University", "City", "CUL"] },
  { name: "Coventry University", aliases: ["Coventry"] },
  { name: "Cranfield University", aliases: ["Cranfield"] },
  { name: "University of Cumbria", aliases: ["Cumbria"] },
  { name: "De Montfort University", aliases: ["De Montfort", "DMU"] },
  { name: "University of Derby", aliases: ["Derby"] },
  { name: "University of Dundee", aliases: ["Dundee"] },
  { name: "Durham University", aliases: ["Durham"] },
  { name: "University of East Anglia", aliases: ["East Anglia", "UEA"] },
  { name: "University of East London", aliases: ["East London", "UEL"] },
  { name: "Edge Hill University", aliases: ["Edge Hill"] },
  { name: "University of Edinburgh", aliases: ["Edinburgh", "UoE"] },
  { name: "University of Essex", aliases: ["Essex"] },
  { name: "University of Exeter", aliases: ["Exeter"] },
  { name: "University of Glasgow", aliases: ["Glasgow", "UofG"] },
  { name: "Glasgow Caledonian University", aliases: ["Glasgow Caledonian", "GCU"] },
  { name: "University of Gloucestershire", aliases: ["Gloucestershire", "UoG"] },
  { name: "Goldsmiths, University of London", aliases: ["Goldsmiths", "Gold", "Goldsmiths University"] },
  { name: "University of Greenwich", aliases: ["Greenwich"] },
  { name: "University of Hertfordshire", aliases: ["Hertfordshire", "Herts"] },
  { name: "University of Huddersfield", aliases: ["Huddersfield"] },
  { name: "University of Hull", aliases: ["Hull"] },
  { name: "Imperial College London", aliases: ["Imperial", "ICL"] },
  { name: "University of Keele", aliases: ["Keele"] },
  { name: "University of Kent", aliases: ["Kent"] },
  { name: "King's College London", aliases: ["King's College", "KCL"] },
  { name: "Kingston University", aliases: ["Kingston"] },
  { name: "University of Lancaster", aliases: ["Lancaster"] },
  { name: "University of Leeds", aliases: ["Leeds"] },
  { name: "Leeds Beckett University", aliases: ["Leeds Beckett", "Leeds Beckett", "LBU"] },
  { name: "Leeds Trinity University", aliases: ["Leeds Trinity", "Leeds Trinity", "LTU"] },
  { name: "University of Leicester", aliases: ["Leicester"] },
  { name: "University of Lincoln", aliases: ["Lincoln"] },
  { name: "University of Liverpool", aliases: ["Liverpool", "UoL"] },
  { name: "Liverpool Hope University", aliases: ["Liverpool Hope", "Hope University"] },
  { name: "Liverpool John Moores University", aliases: ["Liverpool John Moores", "LJMU"] },
  { name: "University of London", aliases: ["London", "UoL"] },
  { name: "London Metropolitan University", aliases: ["London Metropolitan", "London Met"] },
  { name: "London School of Economics and Political Science", aliases: ["London School of Economics", "LSE"] },
  { name: "London South Bank University", aliases: ["London South Bank", "LSBU"] },
  { name: "University of Manchester", aliases: ["Manchester", "UoM"] },
  { name: "Manchester Metropolitan University", aliases: ["Manchester Metropolitan", "MMU"] },
  { name: "Middlesex University London", aliases: ["Middlesex University", "Middlesex", "MDX"] },
  { name: "Newcastle University", aliases: ["Newcastle", "NCL"] },
  { name: "University of Northampton", aliases: ["Northampton"] },
  { name: "Northumbria University", aliases: ["Northumbria", "Northumbria Uni"] },
  { name: "University of Nottingham", aliases: ["Nottingham", "UoN"] },
  { name: "Nottingham Trent University", aliases: ["Nottingham Trent", "NTU"] },
  { name: "Open University", aliases: ["Open"] },
  { name: "University of Oxford", aliases: ["Oxford"] },
  { name: "University of Plymouth", aliases: ["Plymouth"] },
  { name: "University of Portsmouth", aliases: ["Portsmouth", "UoP"] },
  { name: "Queen Margaret University, Edinburgh", aliases: ["Queen Margaret University", "QMU"] },
  { name: "Queen Mary University of London", aliases: ["Queen Mary University", "QMUL"] },
  { name: "Queen's University Belfast", aliases: ["Queen's University", "QUB"] },
  { name: "University of Reading", aliases: ["Reading"] },
  { name: "Robert Gordon University", aliases: ["Robert Gordon", "RGU"] },
  { name: "University of Roehampton", aliases: ["Roehampton"] },
  { name: "University of Salford", aliases: ["Salford"] },
  { name: "University of Sheffield", aliases: ["Sheffield"] },
  { name: "Sheffield Hallam University", aliases: ["Sheffield Hallam", "SHU"] },
  { name: "University of Southampton", aliases: ["Southampton"] },
  { name: "Solent University", aliases: ["Solent"] },
  { name: "University of South Wales", aliases: ["South Wales", "USW"] },
  { name: "University of St Andrews", aliases: ["St Andrews"] },
  { name: "University of Stirling", aliases: ["Stirling"] },
  { name: "University of Strathclyde", aliases: ["Strathclyde"] },
  { name: "University of Suffolk", aliases: ["Suffolk"] },
  { name: "University of Sunderland", aliases: ["Sunderland"] },
  { name: "University of Surrey", aliases: ["Surrey"] },
  { name: "University of Sussex", aliases: ["Sussex"] },
  { name: "Swansea University", aliases: ["Swansea"] },
  { name: "Teesside University", aliases: ["Teesside", "TU"] },
  { name: "University of the Arts London", aliases: ["University of the Arts", "UAL"] },
  { name: "University of Ulster", aliases: ["Ulster"] },
  { name: "University of Wales", aliases: ["Wales"] },
  { name: "University of Warwick", aliases: ["Warwick","UOW"] },
  { name: "University of the West of England, Bristol", aliases: ["University of the West of England", "UWE Bristol"] },
  { name: "University of the West of Scotland", aliases: ["University of the West of Scotland", "UWS"] },
  { name: "University of West London", aliases: ["West London", "UWL"] },
  { name: "University of Westminster", aliases: ["Westminster"] },
  { name: "University of Winchester", aliases: ["Winchester"] },
  { name: "University of Wolverhampton", aliases: ["Wolverhampton"] },
  { name: "University of Worcester", aliases: ["Worcester"] },
  { name: "University of York", aliases: ["York"] },
];

function getUniversities() {
  return universities;
}
